DROP TABLE IF EXISTS quiz CASCADE;
CREATE TABLE quiz (
  id SERIAL PRIMARY KEY NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  subject VARCHAR (255) NOT NULL,
  public BOOLEAN DEFAULT FALSE,
  question_id TEXT NOT NULL
);
